disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - force_cast
  - large_tuple
included:
  - RPI Tours
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
