# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RPI Tours' do

source 'https://github.com/CocoaPods/Specs.git'
pod 'Mapbox-iOS-SDK'
pod 'SwiftyJSON'
pod 'CSwiftV', :git => 'https://github.com/Daniel1of1/CSwiftV.git'

pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :branch => 'swift3'
pod 'ReachabilitySwift', '~> 3'
pod 'TNImageSliderViewController', :git=> 'https://github.com/JohnBehnke/TNImageSliderViewController.git'
pod 'Polyline', '~> 4.0'
pod 'Alamofire', '~> 4.4'
end

target 'RPI ToursTests' do

end

target 'RPI ToursUITests' do

end

