# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RPI Tours' do

source 'https://github.com/CocoaPods/Specs.git'
pod 'Mapbox-iOS-SDK'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'CSwiftV', :git => 'https://github.com/Daniel1of1/CSwiftV.git'
pod 'Alamofire', '~> 3.4'
pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :tag => 'v0.6.0'
pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift.git'
pod 'TNImageSliderViewController', :git=> 'https://github.com/frederik-jacques/TNImageSliderViewController.git'
end

target 'RPI ToursTests' do

end

target 'RPI ToursUITests' do

end

